// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxcmgmtdrfqlmwdnjagv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4Y21nbXRkcmZxbG13ZG5qYWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MjA0ODQsImV4cCI6MjA3NDM5NjQ4NH0.BICzeCC8abnk3y4I9mo1T_sPKj8nIV0Q1-uIOGB9cVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});